# Generated by Django 5.0 on 2023-12-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_signaturefeature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturefeature",
            name="contour_features",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signaturefeature",
            name="frequency_features",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signaturefeature",
            name="geometric_features",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signaturefeature",
            name="pixel_statistics",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signaturefeature",
            name="texture_features",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
