# Generated by Django 5.0 on 2023-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_signaturefeature_contour_features_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signaturefeature",
            name="contour_features",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="signaturefeature",
            name="frequency_features",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="signaturefeature",
            name="geometric_features",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="signaturefeature",
            name="pixel_statistics",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="signaturefeature",
            name="texture_features",
            field=models.JSONField(null=True),
        ),
    ]
