# Generated by Django 5.0 on 2023-12-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_signaturefeature_contour_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturefeature",
            name="name",
            field=models.CharField(default="", max_length=128, verbose_name="Имя пользователя"),
            preserve_default=False,
        ),
    ]
